# -*- Mode: python; py-indent-offset: 4; indent-tabs-mode: nil; coding: utf-8; -*-

def build(bld):

    obj = bld.create_ns3_program('weep-wifi-sim', ['weep', 'core', 'wifi', 'internet', 'applications'])
    obj.source = [
        'benchmark-main.cc',
        'benchmark-utils.cc',
        'weep-wifi-sim.cc',
        ]

